[package]
name = "netstatsd"
version = "0.2.0"
edition = "2021"

[dependencies]
again = "0.1"
anyhow = "1.0"
base64 = "0.13.0"
ed25519-dalek = { version = "1.0.1" }
env_logger = "0.9.0"
log = "0.4.14"
reqwest = { version = "0.11.9", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subprocess = "0.2.8"
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
holochain = "0.1.3"
holochain_types = "0.1.3"
holochain_websocket = "0.1.0"
url = "2.2"

[dependencies.hpos-config-core]
git = "https://github.com/Holo-Host/hpos-config"
rev = "607bdca7f3ee74749994642e197c18aca3eb8e43"

[dependencies.hpos-config-seed-bundle-explorer]
git = "https://github.com/Holo-Host/hpos-config"
rev = "607bdca7f3ee74749994642e197c18aca3eb8e43"
